name: Java CI with Gradle

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '30 3 ***'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Release'
  pull_request:
    branches:
      - main
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
        gradle-version: 7.4.1
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Clean with Gradle
      run: ./gradlew clean
    - name: Check with Gradle
      run: ./gradlew check
    - name: Build with Gradle
      run: ./gradlew build
